Change stuff to fit our discord
lambda-client/bot-kt-plugins pull request #1
Opened 2021-04-29 10:56 UTC by Natan515

Don't marge yet, I won't to change some more stuff.

2021-04-29 11:22 UTC, Natan515 commented
Ok you can add it now.

2021-04-29 23:16 UTC, l1ving commented on LICENSE.md
> +Copyright (c) 2020
Why do you think you can just do this?
If you really want to bump the copyright, add `lambda-client` on the second line.

2021-04-29 23:19 UTC, l1ving requested changes

2021-04-29 23:19 UTC, l1ving commented on LICENSE.md
> +Copyright (c) 2020
```suggestion
Copyright (c) 2020, Liv <~@l1v.in>
Copyright (c) 2021, lambda-client
```

2021-04-29 23:19 UTC, l1ving commented on kami-blue-plugin/resources/plugin_info.json
> +  "authors": ["Liv, Constructor"],
I don't see Constructor's commits anywhere in this pull?

2021-04-29 23:19 UTC, l1ving commented on kami-blue-plugin/src/org/kamiblue/botkt/plugins/main/commands/InstallCommand.kt
> +                    description = "Download this from <#634549110145286156> or from the [website](https://Lambda-client.com/download).\n\nThis is a `1.12.2` [Forge mod](https://files.minecraftforge.n
You updated literally none of these

2021-04-29 23:19 UTC, l1ving commented on kami-blue-plugin/src/org/kamiblue/botkt/plugins/main/commands/SafeCommand.kt
> +                "Keep in mind, the likelyhood of having a Github account with **2fa** and proper password security being hacked is **extremely low**. All of the members of Lambda-client have great pa
You can't even spell password correctly, I doubt this is true

2021-04-29 23:19 UTC, l1ving commented on kami-blue-plugin/src/org/kamiblue/botkt/plugins/main/commands/SafeCommand.kt
>                  "If a commit is not signed, it is **imperative** that you check the contents of the commit yourself, if you'd like to be sure it is safe (ie a pull request was merged without signed c
Your own commits aren't even signed, with the exceptions of the ones you do via the web editor??

2021-04-30 00:22 UTC, huddy987 requested changes

2021-04-30 00:22 UTC, huddy987 commented on LICENSE.md
> +Copyright (c) 2020
Yeah +1, you cannot remove people from the copywrite.

2021-04-30 00:22 UTC, huddy987 commented on kami-blue-plugin/resources/plugin_info.json
> +  "authors": ["Liv, Constructor"],
+1, don't add Constructor

2021-04-30 00:22 UTC, huddy987 commented on kami-blue-plugin/src/org/kamiblue/botkt/plugins/main/KamiBluePlugin.kt
> +        Main.logger.debug("Lambda-client Plugin loading...\n" +
Change all these occurances to just Lambda not Lambda-client please

2021-04-30 00:23 UTC, huddy987 commented
Just a heads up, since we have not yet decided on what to do about the discord bot yet, this may not get merged until we decide and if we decide to continue using this bot.

2021-04-30 04:19 UTC, Natan515 commented
K

2021-04-30 05:38 UTC, Natan515 commented on kami-blue-plugin/src/org/kamiblue/botkt/plugins/main/commands/InstallCommand.kt
> +                    description = "Download this from <#634549110145286156> or from the [website](https://Lambda-client.com/download).\n\nThis is a `1.12.2` [Forge mod](https://files.minecraftforge.n
Dude u told me to remove any credits for u... I would have wanted to give more but U didn't want that...

2021-04-30 05:43 UTC, Natan515 reviewed
Well I have fixed what I have been asked to fix and just to be clear l1ving told me to remove any credit of her... I wanted to give her credit.

2021-04-30 05:43 UTC, Natan515 commented on kami-blue-plugin/src/org/kamiblue/botkt/plugins/main/commands/SafeCommand.kt
>                  "If a commit is not signed, it is **imperative** that you check the contents of the commit yourself, if you'd like to be sure it is safe (ie a pull request was merged without signed c
They will be

2021-04-30 05:43 UTC, Natan515 commented on kami-blue-plugin/src/org/kamiblue/botkt/plugins/main/commands/SafeCommand.kt
> +                "Keep in mind, the likelyhood of having a Github account with **2fa** and proper password security being hacked is **extremely low**. All of the members of Lambda-client have great pa
I fixed it, it was just a typing error

2021-04-30 05:43 UTC, Natan515 commented on LICENSE.md
> +Copyright (c) 2020
Again @l1ving  I wanted to give u credit but u asked me not to!

2021-05-21 09:05 UTC, closed without merging